name: Build and Deploy Code
# run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push,pull_request]

jobs:
  job1: 
    environment: 
      name: testing
    # env:
    #   DATABASE_HOSTNAME: ${{secret.DATABASE_HOSTNAME}}
    #   DATABASE_PORT: 5432
    #   DATABASE_PASSWORD: password123
    #   DATABASE_USERNAME: postgres
    #   DATABASE_NAME: postgres
    #   SECRET_KEY: 09d25e094faa6ca2556c818166b7a9563b93f7099f6f0f4caa6cf63b88e8d3e7
    #   ACCESS_TOKEN_EXPIRE_MINUTES: 60
    #   ALGORITHM: S256

    runs-on: ubuntu-latest
    steps:
      - name: Pulling git repo
        uses: actions/checkout@v2
      - name: Install Python version 3.9
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"
      - name: update pip
        run: python -m pip install --upgrade pip
      - name: Installing all dependencies
        run: pip install -r requirements.txt
      - name: test with pytest
        run: |
          pip install pytest
          pytest

